baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "DataFest"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "ASA DataFest"
  bio = ""
  job = ""
  location = "Duke University"
  gravatarEmail = "mine@stat.duke.edu"
  # Your profile picture
#  picture = ""
  twitter = "dukedatafest"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "signup"
  name = "Sign up"
  pre = "<i class='fas fa-user-plus fa-lg'></i>"
  url = "/signup"
[[menu.main]]
  weight = 3
  identifier = "workshops"
  name = "workshops"
  pre = "<i class='fas fa-code fa-lg'></i>"
  url = "/workshops"
[[menu.main]]
  weight = 4
  identifier = "schedule"
  name = "Schedule"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/schedule"
[[menu.main]]
  weight = 5
  identifier = "sponsors"
  name = "Sponsors"
  pre = "<i class='fas fa-life-ring'></i>"
  url = "/sponsors"
[[menu.main]]
  weight = 6
  identifier = "media"
  name = "Media"
  pre = "<i class='fas fa-newspaper'></i>"
  url = "/media"
[[menu.main]]
  weight = 7
  identifier = "coc"
  name = "COC"
  pre = "<i class='fas fa-users'></i>"
  url = "/coc"
[[menu.main]]
  weight = 8
  identifier = "faq"
  name = "FAQ"
  pre = "<i class=\"material-icons\">help</i>"
  url = "/faq"


[[menu.footer]]
  weight = 1
  identifier = "Duke"
  name = "Duke StatSci"
  pre = "<i class=\"button-icon fa fa fa-map-marker\"></i>"
  url = "http://stat.duke.edu/"
[[menu.footer]]
  weight = 2
  name = "ASA DataFest"
  pre = "<i class=\"button-icon fa fa fa-chart-bar\"></i>"
  url = "https://ww2.amstat.org/education/datafest/"
[[menu.footer]]
  weight = 3
  identifier = "twitter"
  name = "Twitter"
  pre = "<i class=\"button-icon fa fa fa-twitter\"></i>"
  url = "https://twitter.com/dukedatafest"
[[menu.footer]]


[params]
  dateFormat = "January 2, 2006"
  background = "http://www2.stat.duke.edu/datafest/background.jpg"
  favicon = "http://www2.stat.duke.edu/datafest/favicon.ico"
